### ISSUE TITLE
Actualización de API a nuevos lineamientos de base de datos

### ISSUE THREAD

**Issue by mariaalejandra9404** [udistrital/configuracion_api#42]
Para llevar a cabo esta tarea y mover los datos a la nueva base de datos core se debe:

- [x] Crear el archivo SQL correspondiente al esquema 'configuracion' que se va a mover
- [x] Crear los archivos de migración (Bee migrate) para crear esquemas y tablas
- [x] Redesplegar en TEST para que se cree el esquema y sus tablas
- [x] Mover los datos de un esquema a otro a través de jobs.
- [x] Nivelar secuencias.

**Comment by mariaalejandra9404** [comment]
Se crea rama dev y se jala todo lo que está en test para trabajar apartir de allí

**Comment by mariaalejandra9404** [comment]
Se realizó redespliegue apuntando a nueva base de datos y se solicita revisión de equipo de Configuración para verificar que todo quedó bien. 
http://pruebasapi.intranetoas.udistrital.edu.co:8086/v1/aplicacion

**Comment by fabianLeon** [comment]
- Se valida migración de datos.
- Se realiza solicitud de ajuste de secuencias a equipo de bases de datos.
- Se vallida ajustes de secuencias para configuración de menús y notificaciones por medio de cliente de [configuracion](https://pruebasconfiguracion.portaloas.udistrital.edu.co/#/).
- Datos migrados correctamente, secuencias actualizadas, tablas parametricas de notificaciones,Todo funcionando Ok. 

Gracias @udistrital/core
