### ISSUE TITLE
Validación y Ajustes

### ISSUE THREAD

**Issue by a52290451** [udistrital/configuracion_api#62]
Presentar los avances realizados en cuanto a las tareas contempladas para el primer sprint relacionado con la Migración de Datos a los interesados (Usuarios DBAs) para su validación y realizar los ajustes necesarios.

**Criterio de aceptación**

- [x] Acta de entregables firmada por las partes involucradas, asociada al primer sprint.

**Comment by AlejaB18** [comment]
Se realizó reunión de entrega con los DBAs, en los cuales se presentó la forma de trabajar, el como avanzaba el desarrollo de la migración, errores presentados y scripts modificados sobre tablas, vistas, triggers y constrains. El enlace de la grabación de la reunión puede ser accedido [aquí](https://drive.google.com/file/d/1DdjrgFlMV8f_fZhOQcKt3isRnfdl9siF/view?usp=drive_web&authuser=1).
