### ISSUE TITLE
Presentación de avances en Migración de datos Oracle - PostgreSQL

### ISSUE THREAD

**Issue by a52290451** [udistrital/configuracion_api#75]
Registrar presentación de avances en Migración de datos Oracle - PostgreSQL, realizada el día 31 de enero de 2022.

**Criterios de aceptación**

- [x] Grabación de la reunión.
- [x] Compromisos adquiridos.

**Comment by AlejaB18** [comment]
Se da primera reunión de solicitud de plan de trabajo para el desarrollo de pruebas funcionales y se presenta avance de migración, como conclusión del espacio se solicita avanzar en aún más esquemas para poder ejecutar pruebas, se solicita un espacio de reunión para configuración de una instancia de pruebas, tal como se presenta en la siguiente [grabación](https://drive.google.com/file/d/1NwUw1uXM2DzCsVCmgdGvlPOA8w5i0DQ1/view?usp=sharing).

**Comment by AlejaB18** [comment]
Para Enero 31 se genera una siguiente reunión de validación de avance con la presentación de los esquemas migrados, la confirmación de la no necesidad de migrar demás esquemas dado que se encuentran vacíos, se indica que aún hay esquemas que tienen algunos errores y se solicita plan de trabajo para el desarrollo de pruebas funcionales, como conclusión se indica que se realizará mesas de trabajo todos los jueves durante dos horas, tal como se registra en la siguiente [grabación](https://drive.google.com/file/d/1PM59_-Xv8XNrBjWIZPLW8rcdsPAfTseI/view?usp=drivesdk).

**Comment by AlejaB18** [comment]
Para el día 03 de febrero se dio la primera reunión de pruebas funcionales en que se validó conexión a la bd de migración, con la instancia de pruebas creada para el fin propuesto. La grabación de dicha reunión se relaciona en el siguiente [enlace](https://drive.google.com/file/d/1Tfk-LWVb-dSI9zV7-VjASdOqzQ5oVB3U/view?usp=sharing).

Por otro lado, se definió la estrategia de pruebas y la asignación de responsabilidades sobre los diferentes módulos que se podían probar tal como se relaciona en el siguiente [archivo](https://docs.google.com/spreadsheets/d/1LIj-9nYWIpA-XSJFp1BQb3_BlVTCy5SDum_xa4tHsB0/edit#gid=1097398446).

Adicionalmente, se creó un chat grupal para comunicación constante sobre el avance de las pruebas y solución de inquietudes. Tal cómo se evidencia en la siguiente imagen: 
![image](https://user-images.githubusercontent.com/85303858/154119293-b374244f-02c4-4ff9-80ad-f87b3d5d6252.png)
